config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: "homes#index"
  ActiveAdmin.routes(self)
  resources :users
  resources :stores
  resources :coupons
  resources :products
  resources :brands
  resources :categories
  resources :carts
  resources :orders
  get '/*buyer', to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

    def initialize(user)
    user ||= AdminUser.new
    if user.role == 'admin'
      # can :manage, :all
      can [:read, :update ,:create], Store 
      can [:read, :update ,:create], Category
      can [:read, :update ,:create], Brand
      can [:read, :update ,:create], Coupon
      can [:read, :update ,:create], AdminUser
      can :read, ActiveAdmin::Page, name: "Dashboard", namespace_name: "admin"

    else
      can [:read, :update ,:destroy], Product , :store_id => user.store.id
      can [:create] , Product 
      can [:read, :update], Order , :store_id => user.store.id
      # can [:read, :update], Store , :id => user.store.id
      can :read, ActiveAdmin::Page, name: "Dashboard", namespace_name: "admin"

    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  has_one :store
    def display_name
     email
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :product

    def self.get_carts_of_current_user(user)
        Cart.where(:user_id  => user.id)
    end
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :users
  validates :amount, presence: true ,:numericality => { greater_than_or_equal_to: 1 ,only_integer: true }
  validates :code, presence: true ,uniqueness: true
  validates :limit, presence: true
  validates :expire_at , presence: true
  
  def self.is_valid?(code , user_id)
      coupon=Coupon.find_by(code: code)
        if coupon #&& !UserCoupon.already_used?(user_id,code)
          (coupon.expire_at.nil? || coupon.expire_at >= Date.current) &&
          (coupon.limit == 0 || coupon.limit > coupon.used)
          return true
        end
      return false
  end
  def self.discounted_price(price,code,user_id)
    coupon = Coupon.find_by(code: code)
    new_price = if is_valid?(code ,user_id)
                  if coupon.percentage
                    price - (price * (coupon.amount/100))
                  else
                    (price - coupon.amount)
                  end
                else
                  price
                end
  return new_price
  end



  def display_name
    code   
  end
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :state
    belongs_to :coupon ,optional: true
    has_and_belongs_to_many :products

    def self.get_carts_of_current_user(user)
        Cart.get_carts_of_current_user(user)
    end

    def self.get_user_orders(user)
        where(:user_id => user.id)
    end

    def self.get_coupon(code)
        coupon=Coupon.find_by(code: code)
    end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :product_images, ProductImagesUploader
  belongs_to :category
  belongs_to :brand
  belongs_to :store
  has_many   :images
  has_and_belongs_to_many :orders
  has_many :users, through: :carts
  has_many :carts
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true  ,:numericality => { greater_than_or_equal_to: 0 }
  validates :in_stock, presence: true  ,:numericality => { greater_than_or_equal_to: 0 }
  validates :product_images, presence: true  
  
  def self.search(search)
    if search
      where(["title LIKE?", "%#{search}%"])
    else
      all
    end
  end
end

app/models/state.rb
class State < ApplicationRecord
    has_many :orders
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :admin_user
  has_and_belongs_to_many :products
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable
  # Include default devise modules.
  include DeviseTokenAuth::Concerns::User

  # TODO: change avatar to be compatible with APIs
  mount_uploader :avatar, AvatarUploader
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  # validates :password_digest, 
  # presence: true, 
  # length: { in: Devise.password_length }, 
  # confirmation: true, 
  # on: :create 
  # validates :password_digest, 
  # allow_nil: true, 
  # length: { in: Devise.password_length }, 
  # confirmation: true, 
  # on: :update
  has_many :products, through: :carts
  has_many :carts
  has_many :coupons
end

app/models/user_coupon.rb
class UserCoupon < ApplicationRecord
    belongs_to :user
    belongs_to :coupon
    def self.already_used?(user_id,code)
        coupon=Coupon.find_by(code: code)
        UserCoupon.find_by(user_id: user_id,coupon_id: coupon.id)
    end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
    # Disable csrf protection for APIs
    protect_from_forgery unless: -> { request.format.json? }

    include DeviseTokenAuth::Concerns::SetUserByToken

    def not_found
        render json: { error: 'not found' }
    end
end

app/controllers/stores_controller.rb
class StoresController < ApiController
  before_action :set_store, only: [:show]

  # GET /stores json
  def index
    @stores = Store.all
    render json: @stores
  end

  # GET /stores/1
  def show
    render json: @store
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.user %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @store.user %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>